spring:
  #MariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost/blog


  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: true
    show-sql: false


  #Redis  configuration unFinish
  data:
    redis:
      port: 6379

  # sso
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 60368141234-mn9eqk4hd2h6m8aps2kfp367pt6novdb.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: ef1fd9d039915c402869
            client-secret: 4c4fe8802f6c354a21d0b05aa88ba781b4699931
server:
  port: 8080


