spring:
  #MariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost/blog


  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: true
    show-sql: false


  #Redis  configuration unFinish
  data:
    redis:
      port: 6379

application:
  security:
    jwt:
      algorithm: SignatureAlgorithm.HS256
      secret-key: EHMcQfTjWnZq4t7wzCFJaNdRgUdasdaffsafdafaf5735727527
      expiration: 1000 * 6000 * 10
      refresh-token:
        expiration: 1000 * 6000 * 10 * 7


    oauth2:
      client:
        registration:
          google:
            client-id: { your google id }
            client-secret: { your google secret }
          github:
            client-id: { your github id }
            client-secret: { your github secret }







server:
  port: 8080


